// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   int N = Integer.parseInt(args[0]);
	   int Timesbig = 0;
	   int Timessmall = 0;
	   double ran = 0.0;

	   while (N>=1) {
			ran = Math.random();
			if (ran>0.5) {
				Timesbig++;
			}
			else {
				Timessmall++;
			}
			
			N = N-1;
	   }
	   
	   	System.out.println("> 0.5:  "+Timesbig+" times");
	   	System.out.println("<= 0.5:  "+Timessmall+" times");

	   if (Timessmall!=0) {
			System.out.println("Ratio:  "+(double)Timesbig/(double)Timessmall);
	   }
	
	}
}
